### PR TITLE
Add persian language

### PR DESCRIPTION
**Pull request by aliruss**

### CODE REVIEW

**Comment by kefranabg** [comment]
Thanks for this @aliruss. @niusha-paks will do a review ASAP!

**Comment by aliruss** [comment]
hi @kefranabg and you'r welcome

**Comment by kefranabg** [comment]
Hi @aliruss, are you ok to consider @niusha-paks review ? 😃

**Comment by kefranabg** [comment]
@all-contributors please add @niusha-paks for review

**Pull request merged**
